# Generated by Django 4.2 on 2023-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_field', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
