# Generated by Django 4.2 on 2023-05-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=30)),
                ('country', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('birthday_date', models.DateTimeField()),
            ],
        ),
    ]
