# Generated by Django 4.2 on 2023-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_userstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstable',
            name='password2',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
