# Generated by Django 4.2 on 2023-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_userstable_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
